-- Add required columns if they don't exist
ALTER TABLE users 
    ADD COLUMN IF NOT EXISTS id INT AUTO_INCREMENT PRIMARY KEY,
    ADD COLUMN IF NOT EXISTS username VARCHAR(255) NOT NULL UNIQUE,
    ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL UNIQUE,
    ADD COLUMN IF NOT EXISTS token VARCHAR(255),
    ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_locked BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS locked_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS last_login DATETIME NULL,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Update indexes
CREATE INDEX IF NOT EXISTS idx_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_email ON users(email);
